### ISSUE TITLE
Harvest Plot

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#59] opened 2015-10-06 14:51 UTC
I am currently having issues with the plots button in the harvest tab. I limited groupings between 1-3 and I still can't it the plots button to function.

**Comment by Huh** [comment] 2015-10-06 16:26
It is working for me.  Can you please provide a reproducible example.  A screenshot of the setup tab would be great.
Did you download the data first?  This tab does not yet have sample size and the like implemented and so there isn't much that tells you nothing is loaded. Josh Nowak 


     On Tuesday, October 6, 2015 8:51 AM, gfrc11752 <notifications@github.com> wrote:
   

 I am currently having issues with the plots button in the harvest tab. I limited groupings between 1-3 and I still can't it the plots button to function. —

**Comment by gfrc11752** [comment] 2015-10-06 16:30
Yes, I downloaded the data first, subset Region 1, units all. species mule deer, sex all. age class adult. Years 2005 – 2014, table looks good, just no plot

**Comment by Huh** [comment] 2015-10-06 16:43
You have to pick at least one summarize by option to get the plot.  This is something I will fix in the future.
You can pick as many subset operations as you want, but you have to pick 1 - 4 summarize by options.
Sorry that wasn't clear. Josh Nowak 


     On Tuesday, October 6, 2015 10:30 AM, gfrc11752 <notifications@github.com> wrote:
   

 Yes, I downloaded the data first, subset Region 1, units all. species mule deer, sex all. age class adult. Years 2005 – 2014, table looks good, just no plot

**Comment by Huh** [comment] 2015-10-06 16:46
Actually, you can trick it to plot without extra data manipulations.  Given your example above summarize by species, of which there is only one and so you get the intended result. Josh Nowak 


     On Tuesday, October 6, 2015 10:43 AM, Josh Nowak <Joshnwk@yahoo.com> wrote:
   

 You have to pick at least one summarize by option to get the plot.  This is something I will fix in the future.
You can pick as many subset operations as you want, but you have to pick 1 - 4 summarize by options.
Sorry that wasn't clear. Josh Nowak 


     On Tuesday, October 6, 2015 10:30 AM, gfrc11752 <notifications@github.com> wrote:
   

 Yes, I downloaded the data first, subset Region 1, units all. species mule deer, sex all. age class adult. Years 2005 – 2014, table looks good, just no plot

**Comment by gfrc11752** [comment] 2015-10-06 17:26
I did that as well and all I get is a edit plot button with a blank screen.

**Comment by gfrc11752** [comment] 2015-10-06 17:28
It works in internet explorer but not google chrome…Browser issue!

**Comment by Huh** [comment] 2015-10-06 17:30
It works in Chrome for me, so setting issue of some sort?   Josh Nowak 


     On Tuesday, October 6, 2015 11:29 AM, Josh Nowak <Joshnwk@yahoo.com> wrote:
   

 Sounds like your internet browser or some IT setting is causing the problem, sorry.  
Your phone or perhaps another browser might work if the above is the problem.
Out of curiosity, can you see a plot under each and every gray box on this link:  https://cran.r-project.org/web/packages/googleVis/vignettes/googleVis_examples.html I can go back to some more traditional plot if this is the case.
Josh Nowak 


     On Tuesday, October 6, 2015 11:26 AM, gfrc11752 <notifications@github.com> wrote:
   

 I did that as well and all I get is a edit plot button with a blank screen.

**Comment by Huh** [comment] 2015-10-06 17:32
Sounds like your internet browser or some IT setting is causing the problem, sorry.  
Your phone or perhaps another browser might work if the above is the problem.
Out of curiosity, can you see a plot under each and every gray box on this link:  https://cran.r-project.org/web/packages/googleVis/vignettes/googleVis_examples.html I can go back to some more traditional plot if this is the case.
Josh Nowak 


     On Tuesday, October 6, 2015 11:26 AM, gfrc11752 <notifications@github.com> wrote:
   

 I did that as well and all I get is a edit plot button with a blank screen.

**Comment by gfrc11752** [comment] 2015-10-06 17:36
Yes, those plots do appear under the gray boxes.

**Comment by gfrc11752** [comment] 2015-10-06 17:38
That edit plot button is amazing!! I think I am going to trouble shoot the browser setting because I am really liking what you have here.

**Comment by Huh** [comment] 2015-10-06 17:42
Good deal!
I will work out the sizing stuff in due time, but it is a html/javascript/geeky issue and is not related to functionality....certainly is not pretty though.  Bill Gates once wrote "Clippy must die", similarly I will be hunting down those scroll bars shortly. Josh Nowak 


     On Tuesday, October 6, 2015 11:38 AM, gfrc11752 <notifications@github.com> wrote:
   

 That edit plot button is amazing!! I think I am going to trouble shoot the browser setting because I am really liking what you have here.

**Comment by gfrc11752** [comment] 2015-10-06 17:50
haha, sounds good.

**Comment by Huh** [comment] 2015-12-03 19:45
Can we close this?

I know that we will improve the plots and build reports, but for the moment I would like to clean up our issues.

**Comment by gfrc11752** [comment] 2015-12-03 19:46
Yep, we got bigger fish to fry!

**Closed** 2015-12-03 19:46 UTC
