### ISSUE TITLE
PopR is Crashing

### ISSUE THREAD

**Issue by 12382** [Huh/PopR_SDGFP#122] opened 2016-06-03 17:24 UTC
I tried to download the data for the survival tab and the system crashes.  Let me know if I need to edit some problem data to get this back up and running.

I also tried to run the Survival Data Check to see if I could find some problems and this is the response I receive when I hit Run:
Error: no applicable method for 'filter_' applied to an object of class "NULL"

Thanks
Lauren Wiechmann

**Comment by Huh** [comment] 2016-06-03 17:42
Hi Lauren,

I looked into it briefly and see where the problem is, but I need to explore the data and the code to see the root of the problem.  I need to run to a meeting right now, but I will let you know the fix in a few hours.

Thank you for reporting this error.

Josh Nowak

**Comment by Huh** [comment] 2016-06-03 19:28
One problem seems to be the very small numbers in the age column.  I assume this is in fractions of a year for new fawn capture.  I will accommodate this on my end.  The age at capture is meant to be more general, but I see utility in this information.

**Comment by Huh** [comment] 2016-06-03 20:08
These 12 animals do not have an ageclass entry

```r
          ID1 ageclass
        (chr)    (int)
1  2016911006        0
2  2016911007        0
3  2016911008        0
4  2016911012        0
5  2016911015        0
6  2016911021        0
7  2016911030        0
8  2016911035        0
9  2016911036        0
10 2016911043        0
11 2016911048        0
12 2016911055        0
```

The following animals do not have a sex entry at all
```r
2015111010
2015221027
2015311028
2015511027
2015711002
```

Finally animal 20161111033 is recorded as both female and male.

I will update the code so that it is more robust to these types of errors in the future.  

Thank you for making the program better!

**Comment by Huh** [comment] 2016-06-03 20:13
Code checked and everything functions properly in the absence of the individuals above.

**Comment by gfrc11752** [comment] 2016-06-03 20:15
Sounds great, thanks. We will have to get those entries fixed up.

**Comment by Huh** [comment] 2016-06-03 20:20
@gfrc11752 or @12382  please make the corrections in the database as detailed in #122.  The next update will include code that is more robust to these issues.  This issue is related to #118 and some changes have already been made to deal with some of the issues pointed out here.  

If you are still having issues or require further assistance please do not hesitate to contact me.

Thanks,
Josh

**Comment by Huh** [comment] 2016-06-10 17:46
New issues?

The following animals are missing sex and or ageclass entries

```r
> filter(xx, ageclass == "NA" | sex == "NA")
Source: local data frame [8 x 3]

         ID1   sex ageclass
       (chr) (chr)    (chr)
1 2015221027    NA   yoy,NA
2 2015311028    NA      yoy
3 2015511027    NA      yoy
4 2015711002    NA      yoy
5 2016911009    NA       NA
6 2016911012    NA       NA
7 2016911014    NA       NA
8 2016911021    NA       NA

```

@HeatherMcW  if you happen to be working with the database today perhaps you can address these entries?

Sorry about these problems, but like I said lots of updates are on the way and they alleviate many of these issues.

Thanks,
Josh

**Comment by gfrc11752** [comment] 2016-06-20 18:58
Did this get resolved? The website is still crashing (survival tab) so I am assuming we still need to fix this...

**Comment by Huh** [comment] 2016-06-20 19:31
I added some new problems below the original issues that were fixed.  The second set of id's are still missing information. I think... Josh Nowak 

    On Monday, June 20, 2016 12:58 PM, gfrc11752 <notifications@github.com> wrote:
 

 Did this get resolved? The website is still crashing (survival tab) so I am assuming we still need to fix this...—

**Comment by Huh** [comment] 2016-06-20 20:23
For the record, the code has been changed so that in the future this will not occur when information is missing.

**Comment by gfrc11752** [comment] 2016-06-21 17:08
Everything should be fixed now but the list of individuals below never were sexed at capture, thus those data do not exist. 

2015111010
2015221027
2015311028
2015511027
2015711002

Heather, could you do a manual data push from Cybertracker to Sequel. I want to make sure the edits I made fixed PopR from crashing?

Thanks!

Kevin

**Comment by Huh** [comment] 2016-06-21 18:55
It works!  Thank you for all your hard work! Josh 

    On Tuesday, June 21, 2016 11:08 AM, gfrc11752 <notifications@github.com> wrote:
 

 Everything should be fixed now but the list of individuals below never were sexed at capture, thus those data do not exist. 2015111010
2015221027
2015311028
2015511027
2015711002Heather, could you do a manual data push from Cybertracker to Sequel. I want to make sure the edits I made fixed PopR from crashing?Thanks!Kevin—

**Closed** 2017-04-11 05:32 UTC
Labels: help wanted
