### ISSUE TITLE
IPM Tab

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#81] opened 2015-12-11 18:26 UTC
I think we are missing data when we subset DAU in the IPM tab. For example, Mule Deer; DAU 2 has 10 survival observations, and DAU 6 has none (We have some in the survival tab). All DAUs should have 4 M:F ratios and 4 Y:F ratios. Please look into this issue.

**Comment by gfrc11752** [comment] 2015-12-11 18:35
Its appearing like DAU 2 Mule Deer is reporting the same number of survival observations as DAU 3 White-tailed Deer. DAU 2 should also have no white-tailed deer survival observations and it appears to me the DAU 2 white-tailed information should be the mule deer data.

**Comment by Huh** [comment] 2015-12-11 18:47
This last comment is complicated because you switch species and DAU, so I don't know what the relationship is.  Can you expand a bit? Josh Nowak 


    On Friday, December 11, 2015 11:35 AM, gfrc11752 <notifications@github.com> wrote:
 

 Its appearing like DAU 2 Mule Deer is reporting the same number of survival observations as DAU 3 White-tailed Deer. DAU 2 should also have no white-tailed deer survival observations and it appears to me the DAU 2 white-tailed information should be the mule deer data. —

**Comment by Huh** [comment] 2015-12-11 19:03
Because the number of DAU's has changed we need to rebuild the IPM database.  The current db relies on the old 6 DAU configuration.

The workflow is as follows:
-  Define DAU's
-  Fit a survival model for each year by sex by age combination
-  Fit a composition model for each year by ... combination
-  Fit a pregnancy model for each year by ... combination

Harvest data reorganization is automatic.

**Comment by gfrc11752** [comment] 2015-12-11 19:08
Alright, do you still need further clarification on my last comment? Sounds like you encountered the problem.

**Comment by Huh** [comment] 2015-12-11 19:10
No, the problem is that I wasn't thinking about the entire workflow.  So, we have to refit all the models now if we have decided on a DAU structure. Josh Nowak 


    On Friday, December 11, 2015 12:08 PM, gfrc11752 <notifications@github.com> wrote:
 

 Alright, do you still need further clarification on my last comment? Sounds like you encountered the problem.—

**Comment by gfrc11752** [comment] 2015-12-11 19:11
Roger that

**Comment by Huh** [comment] 2015-12-15 19:08
I am closing this because our next step to get the IPM database is rather obvious.  We need a reference DAU structure first and then we can move on to rebuild the IPM database.

**Closed by Huh** 2015-12-15 19:08 UTC
